### ISSUE TITLE
1.16.1 Forge server error

### ISSUE THREAD

**Issue by Daejangnamu** [lilypuree/Decorative-Blocks#24]
forge-1.16.1-32.0.108
decorative_blocks-7c

[latest.log](https://github.com/lilypuree/Decorative-Blocks/files/5048689/latest.log)

안녕하세요 한국분이라고 글 본거같아서 한글로 적겠습니다.
다른 모드는 적용한게 없는데 biomesoplenty 관련해서 에러메세지가 나옵니다.
무시해도 상관이 없는건가요?
에러가 엄청 뜨길래 찝찝해서요.

**Comment by lilypuree** [comment]
This is not a breaking issue, so I'll close the issue. You can ignore it. Just happens because the advancements/tags can't be conditionally registered unfortunately, resulting in those annoying error messages about the blocks not existing(The BOP blocks are conditionally registered). There's no convenient way to disable this behavior currently.
한글 모르는 분들을 위해 영어로도 적었는데 그냥 무시하시면 됩니다.
