### ISSUE TITLE
[Bug] Can't go into my own Minecraft Realm when I have this mod in my mods folder

### ISSUE THREAD

**Issue by iMoobert** [lilypuree/Decorative-Blocks#33]
I get the error message: "Connection Lost. / Incomplete set of tags received from server. / Please contact server operator" when the mod is occupying space in my mods folder.
(/ = next line)

I've gone through the list of all of my other mods, this is the only one where there is an issue.

This does not crash my game, it only prevents me from entering my realm.

Forge: 34.1.0
Version: Java 1.16.3

**Comment by Extegral** [comment]
Are you aware that realms are not quite compatible with mods whatsoever? You are getting disconnected because decorative blocks adds fluid tag for thatch, and this tag is not present on server, as much as the mod itself apparently. Tag sets do not match, therefore you won't be able to connect. Same goes for any mods that use vanilla tagging for things like fluids.

**Comment by iMoobert** [comment]
Oof, I was not aware.
It was working for me just fine on 1.16.2, so when I updated to 1.16.3 I just assumed it would work then as well.
Thanks for telling me why it isn't working. I don't know how it was working earlier but I guess I'll have to just swap it in or out depending on realms or single player from now on :c

**Comment by lilypuree** [comment]
1.16.2 and 1.16.3 has almost no difference, idk how you were able to connect on one version but not on 1.16.3. anyway I'll close this issue...
